version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: refaccionaria_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: refaccionaria_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - refaccionaria_network

  app:
    build: .
    container_name: refaccionaria_app
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://admin:admin123@mongodb:27017/refaccionaria_db?authSource=admin
      ADMIN_PASS: artemio123
      PORT: 3000
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
    networks:
      - refaccionaria_network

volumes:
  mongodb_data:

networks:
  refaccionaria_network:
    driver: bridge
